update texts set name="Limit Reverse", desc="Target 1 monster with 1000 or less ATK in your Graveyard; Special Summon it in Attack Position. If the target is changed to Defense Position, destroy it and this card. When this card leaves the field, destroy the target. When the target is destroyed, destroy this card." where id=00027551
;update texts set name="The 13th Grave", desc="A zombie that suddenly appeared from plot #13 - an empty grave." where id=00032864
;update texts set name="D/D Savant Thomas", desc=" Pendulum Effect" where id=00041546
;update texts set name="Gem-Enhancement", desc="Tribute 1 ""Gem-Knight"" monster, then target 1 ""Gem-Knight"" monster in your Graveyard; Special Summon that target from the Graveyard." where id=00041777
;update texts set name="Magician''s Circle", desc="When a Spellcaster-Type monster declares an attack: Each player Special Summons 1 Spellcaster-Type monster with 2000 or less ATK from their Deck in Attack Position." where id=00050755
;update texts set name="Castle of Dark Illusions", desc="FLIP: All Zombie-Type monsters gain 200 ATK and DEF. During each of your next 4 Standby Phases, each of those Zombie-Type monsters gains 200 more ATK and DEF. These effects last as long as this card is face-up on the field." where id=00062121
;update texts set name="Cipher Spectrum", desc="If a ""Cipher"" Xyz Monster(s) you control is destroyed by battle or an opponent''s card effect and sent to your Graveyard while it has Xyz Material: Target 1 of those monsters; Special Summon it, and if you do, Special Summon 1 Xyz Monster with the same name from your Extra Deck." where id=00098905
;update texts set name="Lava Golem", desc="Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) to your opponent''s side of the field by Tributing 2 monsters they control. You cannot Normal Summon/Set the turn you Special Summon this card. During each of your Standby Phases: Take 1000 damage." where id=00102380
;update texts set name="Seismic Crasher", desc="Twice per turn, you can send 1 face-up Continuous Spell or Continuous Trap Card you control to the Graveyard to inflict 500 damage to your opponent." where id=00114932
;update texts set name="Laval Lancelord", desc="You can Normal Summon this card without Tributing. If you do, during the End Phase: Send it to the Graveyard. When this card on the field is destroyed and sent to the Graveyard: You can target 1 of your banished FIRE monsters; add that target to your hand." where id=00123709
;update texts set name="Skull Dice", desc="Roll a six-sided die. All monsters your opponent currently controls lose ATK and DEF equal to the result x 100, until the End Phase." where id=00126218
;update texts set name="Performapal Springoose", desc="You can banish this card from your Graveyard, then target 2 cards among the Pendulum Monsters you control and/or the ""Magician"" and ""Performapal"" cards in your Pendulum Zone; return both to the hand. You can only use this effect of ""Performapal Springoose"" once per turn." where id=00128454
;update texts set name="Miracle Flipper", desc="If you control a ""Miracle Flipper"", you cannot Summon this card. Your opponent cannot select another face-up monster as an attack target. If this card is destroyed by battle, Special Summon it to your opponent''s side of the field at the end of the Battle Phase. If this card is destroyed by the effect of a Spell or Trap Card, destroy 1 monster your opponent controls." where id=00131182
;update texts set name="Key Mouse", desc="When this card is destroyed by battle and sent to the Graveyard, you can add 1 Level 3 or lower Beast-Type monster from your Deck to your hand." where id=00135598
;update texts set name="Mischief of the Gnomes", desc="This turn, reduce the Levels of all monsters in each player''s hand by 1 (even after they are Summoned/Set). You can banish this card from the Graveyard; this turn, reduce the Levels of all monsters in each player''s hand by 1 (even after they are Summoned/Set)." where id=00164710
;update texts set name="Vylon Hept", desc="Once per turn: You can target 1 ""Vylon"" Monster Card you control that is an Equip Card; Special Summon that target in face-up Defense Position. Banish it when it leaves the field." where id=00168917
;update texts set name="Hero Flash!!", desc="Banish ""H - Heated Heart"", ""E - Emergency Call"", ""R - Righteous Justice"" and ""O - Oversoul"" from your Graveyard; Special Summon 1 ""Elemental HERO"" Normal Monster from your Deck. All ""Elemental HERO"" Normal Monsters you currently control can attack your opponent directly this turn." where id=00191749
;update texts set name="E - Emergency Call", desc="Add 1 ""Elemental HERO"" monster from your Deck to your hand." where id=00213326
;update texts set name="Fenrir", desc="This card cannot be Normal Summoned or Set. This card can only be Special Summoned by removing from play 2 WATER monsters in your Graveyard. When this card destroys an opponent''s monster as a result of battle, your opponent skips their next Draw Phase." where id=00218704
;update texts set name="Ballista of Rampart Smashing", desc="If the equipped monster attacks a face-down Defense Position monster, it gains 1500 ATK during damage calculation only." where id=00242146
;update texts set name="Rapid Warrior", desc="During your Main Phase 1, you can activate this card''s effect. If you do, it can attack your opponent directly this turn. Other monsters cannot attack during the turn you activate this effect." where id=00255998
;update texts set name="Inzektor Gauntlet", desc="Target 1 face-up ""Inzektor"" monster you control; equip this card to that target. It gains 1000 DEF, and cannot be destroyed by your opponent''s card effects." where id=00259314
;update texts set name="Mound of the Bound Creator", desc="Level 10 or higher monsters on the field cannot be targeted or destroyed by card effects. If a Level 10 or higher monster on the field destroys a monster by battle and sends it to the Graveyard: The player who controlled the destroyed monster takes 1000 damage. When this card on the field is destroyed by a card effect and sent to the Graveyard: You can add 1 DIVINE monster from your Deck to your hand." where id=00269012
;update texts set name="Shinobird Healing", desc="If a face-up Spirit monster(s) you control is returned to your hand while you control this face-up card (except during the Damage Step): You can target 1 card your opponent controls; destroy it. When an opponent''s monster declares an attack: You can banish 1 Spirit monster from your Graveyard; negate the attack, then end the Battle Phase. You can only use each effect of ""Shinobird Healing"" once per turn." where id=00276357
;update texts set name="Mermail Abyssnose", desc="When this card destroys an opponent''s monster by battle and sends it to the Graveyard: You can discard 1 WATER monster to the Graveyard; Special Summon 1 ""Mermail"" monster from your Deck in face-up Defense Position. You can only use the effect of ""Mermail Abyssnose"" once per turn." where id=00282886
;update texts set name="Jet Warrior", desc="""Jet Synchron"" + 1 or more non-Tuner monstersIf this card is Synchro Summoned: You can target 1 card your opponent controls; return it to the hand. If this card is in your Graveyard: You can Tribute 1 Level 2 or lower monster; Special Summon this card in Defense Position, but banish it when it leaves the field. You can only use each effect of ""Jet Warrior"" once per turn." where id=00286392
;update texts set name="T.G. Warwolf", desc="When a Level 4 or lower monster(s) is Special Summoned (except during the Damage Step): You can Special Summon this card from your hand. During the End Phase, if this card is in the Graveyard because it was destroyed on the field and sent there this turn: You can add 1 ""T.G."" monster from your Deck to your hand, except ""T.G. Warwolf""." where id=00293542
;update texts set name="A Legendary Ocean", desc="This card''s name is treated as ""Umi"". Reduce the Level of all WATER monsters in both players'' hands and on the field by 1. All WATER monsters gain 200 ATK and DEF." where id=00295517
;update texts set name="The Regulation of Tribe", desc="Declare 1 Type of monster. Monsters of the declared Type cannot attack. Tribute 1 monster from your side of the field during each of your Standby Phases. If you do not, this card is destroyed." where id=00296499
;update texts set name="Amplifier", desc="Equip only to ""Jinzo"". While this card is equipped, the equipped monster''s effect does not negate the effects of its controller''s Trap Cards. When this card is removed from the field, destroy the equipped monster. This card''s activation and effect cannot be negated." where id=00303660
;update texts set name="Spell Gear", desc="Send 3 face-up ""Ancient Gear"" cards you control to the Graveyard. You can Special Summon up to 1 ""Ancient Gear Golem"" from your hand and 1 from your Deck, ignoring the Summoning conditions. Then, destroy all monsters you control except ""Ancient Gear Golems"". You cannot Normal Summon or Set until the end of your next turn." where id=00313513
;update texts set name="Gusto Squirro", desc="When this card is destroyed by a card effect and sent to the Graveyard: You can Special Summon 1 Level 5 or higher ""Gusto"" monster from your Deck." where id=00336369
;update texts set name="Performapal Elephammer", desc="If you control 2 or more ""Performapal"" cards, you can Normal Summon this card without Tributing. Cannot attack unless you control another ""Performapal"" card. When this card declares an attack: You can return all Spell and Trap Cards your opponent controls to the hand." where id=00340002
;update texts set name="Evilswarm Nightmare", desc="2 Level 4 DARK monstersWhen your opponent Special Summons a monster(s) (except during the Damage Step): You can detach 1 Xyz Material from this card; change that Special Summoned monster(s) to face-down Defense Position." where id=00359563
;update texts set name="Dinomist Brachion", desc=" Pendulum Effect" where id=00368382
;update texts set name="Gagaga Sister", desc="When this card is Normal Summoned: You can add 1 ""Gagaga"" Spell/Trap Card from your Deck to your hand. You can target 1 other ""Gagaga"" monster you control; the Levels of that monster and this card become their combined current Levels, until the end of this turn. You can only use this effect of ""Gagaga Sister"" once per turn." where id=00387282
;update texts set name="Wattgiraffe", desc="This card can attack your opponent directly. When this card inflicts Battle Damage to your opponent by a direct attack, your opponent cannot activate Spells, Traps, Spell/Trap effects or Monster Cards effect until the End Phase of this turn." where id=00402568
;update texts set name="The A. Forces", desc="All Warrior-Type monsters you control gain 200 ATK for each Warrior or Spellcaster-Type monster you control." where id=00403847
;update texts set name="Summoner Monk", desc="While this card is face-up on the field, it cannot be Tributed. If this card is Normal or Flip Summoned: Change this card to Defense Position. Once per turn: You can discard 1 Spell Card; Special Summon 1 Level 4 monster from your Deck, but that monster cannot attack this turn." where id=00423585
;update texts set name="Gearfried the Iron Knight", desc="When an Equip Card(s) is equipped to this card: Destroy that Equip Card(s)." where id=00423705
;update texts set name="Goblin of Greed", desc="As long as this card remains face-up on your side of the field, neither player can activate an effect by discarding from his/her hand." where id=00425934
;update texts set name="Bahamut Shark", desc="2 Level 4 WATER monstersOnce per turn: You can detach 1 Xyz Material from this card; Special Summon 1 Rank 3 or lower WATER Xyz Monster from your Extra Deck. This card cannot attack for the rest of this turn." where id=00440556
;update texts set name="The Book of the Law", desc="Tribute 1 ""Eidolon Beast"" monster; Special Summon 1 ""Eidolon Beast"" monster with a different original Attribute from your Extra Deck. (This Special Summon is treated as a Fusion Summon.) You can only activate 1 ""The Book of the Law"" per turn." where id=00458748
;update texts set name="Frightfur Tiger", desc="""Edge Imp Sabres"" + 1 or more ""Fluffal"" monstersWhen this card is Fusion Summoned: You can target cards on the field, up to the number of Fusion Materials used for its Fusion Summon; destroy them. All ""Frightfur"" monsters you control gain 300 ATK for each ""Fluffal"" monster and ""Frightfur"" monster you control. You can only control 1 ""Frightfur Tiger""." where id=00464362
;update texts set name="Driving Snow", desc="You can only activate this card when 1 or more of your Trap Cards are destroyed and sent from the field to the Graveyard by a card effect your opponent controls. Destroy 1 Spell or Trap Card on the field." where id=00473469
;update texts set name="Water Spirit", desc="This ancient water spirit haunts the glacial monoliths of Antarctica. It has the power to seep into the pores of any substance and chill it to the bone." where id=00487395
;update texts set name="Superheavy Samurai Warlord Susanowo", desc="1 Machine-Type Tuner + 1 or more non-Tuner ""Superheavy Samurai"" monstersThis card can attack while in face-up Defense Position. If it does, apply its DEF for damage calculation. Once per turn, during either player''s turn, if you have no Spell/Trap Cards in your Graveyard: You can target 1 Spell/Trap Card in your opponent''s Graveyard; Set it to your side of the field, but banish it when it leaves the field." where id=00494922
;update texts set name="Cherry Inmato", desc="When this card is destroyed by battle and sent to the Graveyard, you can Special Summon up to 2 ""Inmato"" monsters from your Deck. The monster(s) Special Summoned by this effect cannot be used as Synchro Material Monsters this turn." where id=00525110
;update texts set name="Prevent Rat", desc="This creature is shielded with a tough hide of hair and is excellent at defending itself." where id=00549481
;update texts set name="Totem Dragon", desc="This card can be treated as 2 Tributes for the Tribute Summon of a Dragon-Type monster. If this card is in your Graveyard during your Standby Phase and you control no monsters, you can Special Summon this card in Attack Position. You cannot activate this effect if there are any monsters in your Graveyard that are not Dragon-Type. If this card is Special Summoned with this effect, remove it from play when it is removed from the field." where id=00564541
;update texts set name="PSY-Frame Circuit", desc="If a ""PSY-Frame"" monster(s) is Special Summoned to your side of the field (except during the Damage Step), you can: Immediately after this effect resolves, Synchro Summon 1 Synchro Monster, using only ""PSY-Frame"" monsters you control. At the start of the Damage Step, if a ""PSY-Frame"" monster you control battles an opponent''s monster: You can discard 1 ""PSY-Frame"" monster; your battling monster gains ATK equal to the discarded monster''s ATK until the end of this turn." where id=00575512
;update texts set name="Daigusto Emeral", desc="2 Level 4 monstersOnce per turn: You can detach 1 Xyz Material from this card, then activate 1 of these effects.● Target 3 monsters in your Graveyard; shuffle all 3 into the Deck, then draw 1 card.● Target 1 non-Effect Monster in your Graveyard; Special Summon that target." where id=00581014
;update texts set name="Snake Fang", desc="Decrease 1 selected monster''s DEF by 500 points during the turn this card is activated." where id=00596051
;update texts set name="Malefic Rainbow Dragon", desc="This card cannot be Normal Summoned or Set. This card cannot be Special Summoned, except by removing from play 1 ""Rainbow Dragon"" from your hand or Deck. There can only be 1 face-up ""Malefic"" monster on the field. Other monsters you control cannot declare an attack. If there is no face-up Field Spell Card on the field, destroy this card." where id=00598988
;update texts set name="Virgil, Rock Star of the Burning Abyss", desc="1 Tuner + 1 or more non-Tuner monstersYou can only control 1 ""Virgil, Rock Star of the Burning Abyss"". Once per turn: You can discard 1 ""Burning Abyss"" card, then target 1 card your opponent controls or in their Graveyard; shuffle it into the Deck. If this card on the field is destroyed by battle or card effect and sent to the Graveyard: You can draw 1 card. You can only use this effect of ""Virgil, Rock Star of the Burning Abyss"" once per turn." where id=00601193
;update texts set name="Gladiator Beast Retiari", desc="When this card is Special Summoned by the effect of a ""Gladiator Beast"" monster, you can remove from play 1 card from your opponent''s Graveyard. At the end of the Battle Phase, if this card attacked or was attacked, you can return it to the Deck to Special Summon 1 ""Gladiator Beast"" monster from your Deck, except ""Gladiator Beast Retiari""." where id=00612115
;update texts set name="Majespecter Toad - Ogama", desc="When this card is Normal or Special Summoned: You can Set 1 ""Majespecter"" Spell/Trap Card directly from your Deck, but it cannot activate this turn. You can only use this effect of ""Majespecter Toad - Ogama"" once per turn. Cannot be targeted or destroyed by your opponent''s card effects." where id=00645794
;update texts set name="Alien Ammonite", desc="When this card is Normal Summoned, you can Special Summon 1 Level 4 or lower ""Alien"" monster from your Graveyard. Destroy it during the End Phase." where id=00652362
;update texts set name="Dark Eruption", desc="Target 1 DARK monster with 1500 or less ATK in your Graveyard; add that target to your hand." where id=00674561
;update texts set name="Zodiac Sign", desc="All ""Zoodiac"" monsters you control gain 300 ATK and DEF. Monsters your opponent controls cannot target Beast-Warrior-Type monsters you control for attacks, except the Beast-Warrior-Type monster you control with the highest ATK (either, if tied). Once per turn, if a ""Zoodiac"" monster(s) you control would be destroyed by a card effect, you can destroy 1 other monster in your hand or field instead." where id=00675319
;update texts set name="Solar Recharge", desc="Discard 1 ""Lightsworn"" monster; draw 2 cards, then send the top 2 cards of your Deck to the Graveyard." where id=00691925
;update texts set name="Thunder End Dragon", desc="2 Level 8 Normal MonstersOnce per turn: You can detach 1 Xyz Material from this card; destroy all other monsters on the field." where id=00698785
;update texts set name="Atlantean Marksman", desc="When this card inflicts battle damage to your opponent: You can Special Summon 1 Level 4 or lower ""Atlantean"" Sea Serpent-Type monster from your Deck, except ""Atlantean Marksman"". When this card is sent to the Graveyard to activate a WATER monster''s effect: Target 1 Set card your opponent controls; destroy that target." where id=00706925
;update texts set name="Amazoness Village", desc="All ""Amazoness"" monsters gain 200 ATK. Once per turn, when an ""Amazoness"" monster is destroyed by battle or by a card effect and sent to the Graveyard: You can Special Summon 1 ""Amazoness"" monster from your Deck with a Level less than or equal to that ""Amazoness"" monster in the Graveyard." where id=00712559
;update texts set name="Temple of Skulls", desc="A mysterious temple of skulls and bones that pulls in unsuspecting enemies." where id=00732302
;update texts set name="Rubic, Malebranche of the Burning Abyss", desc="If you control a monster that is not a ""Burning Abyss"" monster, destroy this card. Cannot be used as a Synchro Material, except for the Synchro Summon of a ""Burning Abyss"" Synchro Monster. If you control no Spell/Trap Cards: You can Special Summon this card from your hand. You can only use this effect of ""Rubic, Malebranche of the Burning Abyss"" once per turn." where id=00734741
;update texts set name="Doron", desc="This monster splits in two and attacks from opposite sides." where id=00756652
;update texts set name="Hiita the Fire Charmer", desc="FLIP: Target 1 face-up FIRE monster your opponent controls; take control of that target while this card is face-up on the field." where id=00759393
;update texts set name="Empress of Prophecy", desc="2 Level 5 Spellcaster-Type monstersThis card gains 300 ATK for each Xyz Material attached to a monster you control. Once per turn: You can detach 1 Xyz Material from this card; shuffle your Deck, then excavate the top 5 cards of your Deck, destroy monsters on the field up to the number of ""Spellbook"" cards excavated, also, after that, place the excavated cards on the top of the Deck in any order." where id=00770365
;update texts set name="Super Soldier Shield", desc="When a Spell/Trap Card, or monster effect, is activated that targets a monster(s) on the field, while you control a ""Black Luster Soldier"" monster: Negate the activation, and if you do, destroy that card. If this card is in your Graveyard: You can remove 1 Spell Counter from your side of the field; Set this card, but banish it when it leaves the field." where id=00799183
;update texts set name="D/D/D Contract Change", desc="When an opponent''s monster declares an attack: Activate 1 of these effects;● Banish 1 ""D/D/D"" monster from your Graveyard, and if you do, the attacking monster loses ATK equal to the banished monster''s ATK.● Add 1 Level 4 or lower ""D/D"" Pendulum Monster from your Deck to your hand." where id=00811734
;update texts set name="Number Wall", desc="Activate only if you control a ""Number"" monster. ""Number"" monsters on the field cannot be destroyed by card effects, and cannot be destroyed by battle except with another ""Number"" monster. When a ""Number"" monster you control is destroyed, destroy this card." where id=00847915
;update texts set name="Dragunity Arma Mystletainn", desc="You can Special Summon this card from your hand by sending 1 face-up ""Dragunity"" monster you control to the Graveyard. When this card is Normal or Special Summoned from the hand, you can select 1 Dragon-Type ""Dragunity"" monster in your Graveyard, and equip it to this card." where id=00876330
;update texts set name="Dragunity Knight - Gae Bulg", desc="1 Dragon-Type Tuner + 1 or more non-Tuner Winged Beast-Type monsters  If this card attacks or is attacked, during the Damage Step you can remove from play 1 (only) Winged Beast-Type monster from your Graveyard, to have this card gain the ATK of that monster until the End Phase." where id=00900787
;update texts set name="Vertical Landing", desc="Tribute any number of WIND monsters, except Tokens; Special Summon an equal number of ""Mecha Phantom Beast Tokens"" (Machine-Type/WIND/Level 3/ATK 0/DEF 0). You can only activate 1 ""Vertical Landing"" per turn." where id=00904185
;update texts set name="Unexpected Dai", desc="If you control no monsters: Special Summon 1 Level 4 or lower Normal Monster from the Deck." where id=00911883
;update texts set name="Gagagatag", desc="All ""Gagaga"" monsters you currently control gains 500 ATK for each ""Gagaga"" monster you currently control, until your next Standby Phase. You can only activate 1 ""Gagagatag"" per turn." where id=00917796
;update texts set name="Geargiarmor", desc="Once per turn: You can change this card to face-down Defense Position. When this card is flipped face-up: You can add 1 ""Geargia"" monster from your Deck to your hand, except ""Geargiarmor""." where id=00923596
;update texts set name="Penalty Game!", desc="When your opponent has 4 cards in their hand: Activate 1 of these effects.● Your opponent cannot draw during their next Draw Phase.● Your opponent cannot activate Spell/Trap Cards this turn." where id=00967928
;update texts set name="Armed Dragon LV3", desc="During your Standby Phase: You can send this face-up card to the Graveyard; Special Summon 1 ""Armed Dragon LV5"" from your hand or Deck." where id=00980973
;update texts set name="Half Unbreak", desc="Target 1 monster on the field; this turn, that monster cannot be destroyed by battle, also any battle damage you take from attacks involving that monster is halved." where id=00981540
;update texts set name="Rebound", desc="When your opponent activates a Spell Card, Trap Card, or monster effect that returns a card(s) from the field to the hand: Negate that effect, and if you do, send 1 card from your opponent''s hand (at random) or from their side of the field to the Graveyard. When this Set card is destroyed by your opponent''s card effect and sent to the Graveyard: Draw 1 card." where id=00983995
;update texts set name="Expressroid", desc="When this card is Summoned: You can target 2 ""roid"" monsters in your Graveyard, except ""Expressroid""; add those targets to your hand." where id=00984114
;update texts set name="D/D/D Gust King Alexander", desc="1 ""D/D"" Tuner + 1 or more non-Tuner monstersIf another ""D/D"" monster(s) is Normal or Special Summoned to your field, while you control this face-up card (except during the Damage Step): You can target 1 Level 4 or lower ""D/D"" monster in your Graveyard; Special Summon it. You can only use this effect of ""D/D/D Gust King Alexander"" once per turn." where id=00987311
;update texts set name="Doggy Diver", desc="If your opponent controls a monster and all face-up monsters you control (min. 1) are Level 4, you can Special Summon this card (from your hand). You can only Special Summon ""Doggy Diver"" once per turn this way. This card cannot be used as an Xyz Material for an Xyz Summon, except for the Xyz Summon of a Warrior-Type monster." where id=01003028
;update texts set name="Starlight Junktion", desc="You can Tribute 1 Tuner monster; Special Summon 1 ""Synchron"" monster from your Deck with a different Level than the Tributed monster had on the field. During your opponent''s turn, if you Special Summon a Synchro Monster from your Extra Deck: Target 1 card on the field; shuffle it into the Deck. You can only use each effect of ""Starlight Junktion"" once per turn." where id=01003840
;update texts set name="Void Trap Hole", desc="When your opponent Special Summons a monster(s) with 2000 or more ATK: Negate the effects of 1 of those monsters with 2000 or more ATK, and if you do, destroy it." where id=01005587
;update texts set name="Junk Changer", desc="You can only use the following effect of ""Junk Changer"" once per turn. If this card is Normal or Special Summoned: You can target 1 ""Junk"" monster on the field, then activate 1 of these effects;● Increase its Level by 1.● Reduce its Level by 1." where id=01006081
;update texts set name="Painful Decision", desc="Send 1 Level 4 or lower Normal Monster from your Deck to the Graveyard, and if you do, add 1 card with the same name as that card from your Deck to your hand. You can only activate 1 ""Painful Decision"" per turn." where id=01033312
;update texts set name="Misfortune", desc="Select 1 face-up monster your opponent controls. Inflict damage to your opponent equal to half that monster''s original ATK. Your monsters cannot attack this turn." where id=01036974
;update texts set name="Geargiano Mk-II", desc="When this card is Normal or Flip Summoned: You can Special Summon 1 ""Geargia"" monster from your hand or Graveyard in Defense Position." where id=01045143
;update texts set name="Satellarknight Unukalhai", desc="If this card is Summoned: You can send 1 ""tellarknight"" card from your Deck to the Graveyard, except ""Satellarknight Unukalhai"". You can only use this effect of ""Satellarknight Unukalhai"" once per turn." where id=01050186
;update texts set name="Scrapyard", desc="Add 1 ""Scrap"" Tuner monster from your Deck to your hand." where id=01050684
;update texts set name="Magic Planter", desc="Send 1 face-up Continuous Trap Card you control to the Graveyard; draw 2 cards." where id=01073952
;update texts set name="Pyro Clock of Destiny", desc="Move the turn count forward by 1 turn. The turn in which this card is activated continues as normal." where id=01082946
;update texts set name="Dark Mimic LV3", desc="If this card is destroyed by battle and sent to the Graveyard: Draw 1 card, but if this card was Special Summoned by the effect of ""Dark Mimic LV1"", draw 2 cards instead." where id=01102515
;update texts set name="Sargasso the D.D. Battlefield", desc="Each time a monster is Xyz Summoned: The Summoning player takes 500 damage. During each player''s End Phase, the turn player takes 500 damage if they control a face-up Xyz Monster." where id=01127737
;update texts set name="Deck Lockdown", desc="Neither player can add cards from their Deck to their hand except by drawing them. Monsters cannot be Special Summoned from the Main Deck. Destroy this card during your 2nd Standby Phase after activation." where id=01149109
;update texts set name="Paleozoic Leanchoilia", desc="Target 1 banished card; return it to the Graveyard. Once per Chain, when a Trap Card is activated while this card is in your Graveyard: Special Summon this card as a Normal Monster (Aqua-Type/WATER/Level 2/ATK 1200/DEF 0). (This card is NOT treated as a Trap Card.) If Summoned this way, this card is unaffected by monster effects, also banish it when it leaves the field." where id=01154611
;update texts set name="Kojikocy", desc="A man-hunter with powerful arms that can crush boulders." where id=01184620
;update texts set name="Mirror of Yata", desc="Equip only to a Spirit monster. The equipped monster does not have to have its effect that returns it to the hand activated. If it would be destroyed by battle, destroy this card instead." where id=01200843
;update texts set name="Malevolent Catastrophe", desc="When an opponent''s monster declares an attack: Destroy all Spell and Trap Cards on the field." where id=01224927
;update texts set name="Chain Destruction", desc="When a monster(s) with 2000 or less ATK is Summoned: Target 1 of them; destroy all cards with that name in its controller''s hand and Main Deck." where id=01248895
;update texts set name="Herald of Pure Light", desc="2 Level 2 monstersYou can detach 1 Xyz Material from this card, then target 1 monster in your Graveyard; add it to your hand, then shuffle 1 card from your hand into the Deck. You can only use the effect of ""Herald of Pure Light"" once per turn." where id=01249315
;update texts set name="Gem-Knight Fusion", desc="Fusion Summon 1 ""Gem-Knight"" Fusion Monster from your Extra Deck, using monsters from your hand or your side of the field as Fusion Materials. If this card is in your Graveyard: You can banish 1 ""Gem-Knight"" monster from your Graveyard; add this card to your hand." where id=01264319
;update texts set name="Kozmo Soartroopers", desc="During either player''s turn: You can banish this card; Special Summon 1 Level 4 or higher ""Kozmo"" monster from your hand. You can only use this effect of ""Kozmo Soartroopers"" once per turn. Once per turn: You can pay 1000 LP, then target 1 Psychic-Type ""Kozmo"" monster in your Graveyard; Special Summon it." where id=01274455
;update texts set name="Vylon Tetra", desc="If this card is sent from the Monster Card Zone to the Graveyard: You can pay 500 Life Points, then target 1 face-up monster you control; equip this card to that target. If the equipped monster would be destroyed, you can destroy this Equip Card instead." where id=01281505
;update texts set name="Prime Material Falcon", desc="When an Effect Monster''s effect to destroy a Spell or Trap Card(s) on the field is activated, you can send 1 card from your hand to the Graveyard to negate its activation and destroy the card." where id=01287123
;update texts set name="T.G. Striker", desc="If your opponent controls a monster and you control no monsters, you can Special Summon this card (from your hand). During the End Phase, if this card is in the Graveyard because it was destroyed on the field and sent there this turn: You can add 1 ""T.G."" monster from your Deck to your hand, except ""T.G. Striker""." where id=01315120
;update texts set name="Mysterious Guard", desc="FLIP: Target 1 face-up monster on the field, and if you control a face-up Warrior-Type monster, you can target 1 additional face-up monster on the field; return the first target to the top of the Deck, then return the additional target (if any) to the hand if you still control a face-up Warrior-Type monster." where id=01347977
;update texts set name="Valhalla, Hall of the Fallen", desc="Once per turn: You can Special Summon 1 Fairy-Type monster from your hand. You must control no monsters to activate and to resolve this effect." where id=01353770
;update texts set name="Ronintoadin", desc="This card''s name is treated as ""Des Frog"" while face-up on the field. You can remove from play 1 ""Frog"" monster in your Graveyard, except ""Frog the Jam"", to Special Summon this card from your Graveyard. This card cannot be used as a Synchro Material Monster." where id=01357146
;update texts set name="Photon Crusher", desc="If this card attacks, it is changed to Defense Position at the end of the Damage Step." where id=01362589
;update texts set name="Vampire Koala", desc="If this card inflicts battle damage to your opponent by battle with a monster: Gain LP equal to the battle damage inflicted." where id=01371589
;update texts set name="Shared Ride", desc="After this card resolves, each time your opponent adds a card(s) from their Deck or Graveyard to their hand this turn with a card effect, except by drawing them, you immediately draw 1 card for each card effect. You can only activate 1 ""Shared Ride"" per turn." where id=01372887
;update texts set name="Hazy Flame Sphynx", desc="Your opponent cannot target this card with card effects. You can declare 1 card type (Monster, Spell, or Trap); send the top card of your Deck to the Graveyard, then if it was the declared card type, you can Special Summon 1 FIRE monster from your hand or Graveyard. You can only use this effect of ""Hazy Flame Sphynx"" once per turn." where id=01409474
;update texts set name="Super Roboyarou", desc="""Roboyarou"" + ""Robolady""You can Special Summon ""Super Robolady"" by returning this card from the field to the Extra Deck. You cannot use this effect during the same turn this monster is Special Summoned. In addition, increase the ATK of this monster by 1000 points during the Damage Step when this monster battles with a monster." where id=01412158
;update texts set name="Number 48: Shadow Lich", desc="2 Level 3 monstersOnce per turn, during your opponent''s turn: You can detach 1 Xyz Material from this card; Special Summon 1 ""Phantom Token"" (Fiend-Type/DARK/Level 1/ATK 500/DEF 500). (This is a Quick Effect.) While you control a ""Phantom Token"", your opponent cannot target this card for attacks. This card gains 500 ATK for each ""Phantom Token"" you control." where id=01426714
;update texts set name="Chaos Necromancer", desc="The ATK of this card is the number of Monster Cards in your Graveyard x 300." where id=01434352
;update texts set name="Dragon Treasure", desc="A Dragon-Type monster equipped with this card increases its ATK and DEF by 300 points." where id=01435851
;update texts set name="Bee List Soldier", desc="You can Tribute this card and 1 face-up Insect-Type monster, except ""Bee List Soldier"", to draw 2 cards." where id=01474910
;update texts set name="Allure of Darkness", desc="Draw 2 cards, then banish 1 DARK monster from your hand, or, if you do not have any in your hand, send your entire hand to the Graveyard." where id=01475311
;update texts set name="Kagemusha of the Six Samurai", desc="During either player''s turn, when exactly 1 face-up ""Six Samurai"" monster you control is targeted by a Spell Card, Trap Card, or card effect that could have targeted this card: You can activate this effect; that Spell/Trap/effect now targets this face-up card on the field, instead." where id=01498130
;update texts set name="Rune-Eyes Pendulum Dragon", desc="""Odd-Eyes Pendulum Dragon"" + 1 Spellcaster-Type monsterIf this card was Fusion Summoned using a Pendulum Summoned monster(s) on the field as Fusion Material, it is unaffected by your opponent''s card effects this turn. Apply the appropriate effect, depending on the original Level of the monster used as Fusion Material that was not ""Odd-Eyes Pendulum Dragon"".● Level 4 or lower: This card can make up to 2 attacks on monsters during each Battle Phase.● Level 5 or higher: This card can make up to 3 attacks on monsters during each Battle Phase." where id=01516510
;update texts set name="The Hunter with 7 Weapons", desc="When this card is Normal Summoned, declare 1 Type of monster. When battling that Type of monster, increase the ATK of this card by 1000 points during Damage Calculation." where id=01525329
;update texts set name="R-Genex Magma", desc="When this card is Normal Summoned, you can add 1 Level 2 ""R-Genex"" monster from your Deck to your hand." where id=01533292
;update texts set name="Space Gift", desc="Draw 1 card for each different ""Neo-Spacian"" name on the monsters you control." where id=01539051
;update texts set name="Cyber End Dragon", desc="""Cyber Dragon"" + ""Cyber Dragon"" + ""Cyber Dragon""A Fusion Summon of this card can only be done with the above Fusion Material Monsters. If this card attacks a Defense Position monster, inflict piercing battle damage to your opponent." where id=01546123
;update texts set name="Rose, Warrior of Revenge", desc="When this card inflicts battle damage to your opponent: Inflict 300 damage to your opponent." where id=01557341
;update texts set name="Silver Bow and Arrow", desc="A Fairy-Type monster equipped with this card increases its ATK and DEF by 300 points." where id=01557499
;update texts set name="ABC-Dragon Buster", desc="""A-Assault Core"" + ""B-Buster Drake"" + ""C-Crush Wyvern""Must first be Special Summoned (from your Extra Deck) by banishing the above cards you control and/or from your Graveyard. (You do not use ""Polymerization"".) Once per turn, during either player''s turn: You can discard 1 card, then target 1 card on the field; banish it. During your opponent''s turn: You can Tribute this card, then target 3 of your banished LIGHT Machine-Type Union monsters with different names; Special Summon them (this is a Quick Effect)." where id=01561110
;update texts set name="White Ninja", desc="FLIP: Target 1 Defense Position monster on the field; destroy that target." where id=01571945
;update texts set name="Dinomist Stegosaur", desc=" Pendulum Effect" where id=01580833
;update texts set name="Deep-Space Cruiser IX", desc="You can Special Summon this card (from your hand) by sending 1 other Machine-Type monster from your hand to the Graveyard." where id=01586457
;update texts set name="Dimension Fortress Weapon", desc="Cards cannot be sent from the Deck to the Graveyard." where id=01596508
;update texts set name="Dark Requiem Xyz Dragon", desc="3 Level 5 monstersIf this card has ""Dark Rebellion Xyz Dragon"" as Xyz Material, it gains these effects.● Once per turn: You can detach 1 Xyz Material from this card, then target 1 face-up monster your opponent controls; change its ATK to 0, and if you do, this card gains ATK equal to that monster''s original ATK.● During either player''s turn, when your opponent activates a monster effect: You can detach 1 Xyz Material from this card; negate the activation, and if you do, destroy that card, then you can Special Summon 1 Xyz Monster from your Graveyard." where id=01621413
;update texts set name="Grand Horn of Heaven", desc="During your opponent''s Main Phase, when they would Special Summon a monster(s): Negate the Summon, and if you do, destroy that monster, then your opponent draws 1 card, then end the Main Phase." where id=01637760
;update texts set name="Divine Dragon Knight Felgrand", desc="2 Level 8 monstersOnce per turn, during either player''s turn: You can detach 1 Xyz Material from this card, then target 1 face-up monster on the field; this turn, its effects are negated, but it is unaffected by other card effects." where id=01639384
;update texts set name="Fusionist", desc="""Petit Angel"" + ""Mystical Sheep #2""" where id=01641882
;update texts set name="Vylon Segment", desc="Equip only to a ""Vylon"" monster. It cannot be targeted by the opponent''s monster effects or Trap effects. If this face-up card on the field is sent to the Graveyard: You can add 1 ""Vylon"" Spell Card from your Deck to your hand." where id=01644289
;update texts set name="Brotherhood of the Fire Fist - Spirit", desc="Cannot be used as a Synchro Material, except for the Synchro Summon of a Beast-Warrior-Type monster. When this card is Normal Summoned: You can target 1 Level 3 FIRE monster with 200 or less DEF in your Graveyard; Special Summon that target in Defense Position, and if you do, monsters you control cannot attack for the rest of this turn, except Beast-Warrior-Type monsters. You can only use this effect of ""Brotherhood of the Fire Fist - Spirit"" once per turn." where id=01662004
;update texts set name="Spell Purification", desc="Discard 1 card from your hand. Destroy all face-up Continuous Spell Cards." where id=01669772
;update texts set name="Ultimaya Tzolkin", desc="(This card''s original Level is always treated as 12.)Cannot be Synchro Summoned. Must be Special Summoned (from your Extra Deck) by sending 2 Level 5 or higher monsters you control with the same Level to the Graveyard (1 Tuner and 1 non-Tuner), and cannot be Special Summoned by other ways. Once per turn, when a Spell/Trap Card(s) is Set on your side of the field (except during the Damage Step): You can Special Summon 1 ""Power Tool"" Synchro Monster or 1 Level 7 or 8 Dragon-Type Synchro Monster from your Extra Deck.  Cannot be targeted for attacks or by card effects, while you control another Synchro Monster." where id=01686814
;