update texts set name="Jet Warrior", desc="""Jet Synchron"" + 1 or more non-Tuner monsters
If this card is Synchro Summoned: You can target 1 card your opponent controls; return it to the hand. If this card is in your Graveyard: You can Tribute 1 Level 2 or lower monster; Special Summon this card in Defense Position, but banish it when it leaves the field. You can only use each effect of ""Jet Warrior"" once per turn." where id=00286392
;update texts set name="Superheavy Samurai Warlord Susanowo", desc="1 Machine-Type Tuner + 1 or more non-Tuner ""Superheavy Samurai"" monsters
This card can attack while in face-up Defense Position. If it does, apply its DEF for damage calculation. Once per turn, during either player''s turn, if you have no Spell/Trap Cards in your Graveyard: You can target 1 Spell/Trap Card in your opponent''s Graveyard; Set it to your side of the field, but banish it when it leaves the field." where id=00494922
;update texts set name="Virgil, Rock Star of the Burning Abyss", desc="1 Tuner + 1 or more non-Tuner monsters
You can only control 1 ""Virgil, Rock Star of the Burning Abyss"". Once per turn: You can discard 1 ""Burning Abyss"" card, then target 1 card your opponent controls or in their Graveyard; shuffle it into the Deck. If this card on the field is destroyed by battle or card effect and sent to the Graveyard: You can draw 1 card. You can only use this effect of ""Virgil, Rock Star of the Burning Abyss"" once per turn." where id=00601193
;update texts set name="Dragunity Knight - Gae Bulg", desc="1 Dragon-Type Tuner + 1 or more non-Tuner Winged Beast-Type monsters 
 If this card attacks or is attacked, during the Damage Step you can remove from play 1 (only) Winged Beast-Type monster from your Graveyard, to have this card gain the ATK of that monster until the End Phase." where id=00900787
;update texts set name="D/D/D Gust King Alexander", desc="1 ""D/D"" Tuner + 1 or more non-Tuner monsters
If another ""D/D"" monster(s) is Normal or Special Summoned to your field, while you control this face-up card (except during the Damage Step): You can target 1 Level 4 or lower ""D/D"" monster in your Graveyard; Special Summon it. You can only use this effect of ""D/D/D Gust King Alexander"" once per turn." where id=00987311
;update texts set name="Starlight Junktion", desc="You can Tribute 1 Tuner monster; Special Summon 1 ""Synchron"" monster from your Deck with a different Level than the Tributed monster had on the field. During your opponent''s turn, if you Special Summon a Synchro Monster from your Extra Deck: Target 1 card on the field; shuffle it into the Deck. You can only use each effect of ""Starlight Junktion"" once per turn." where id=01003840
;update texts set name="Scrapyard", desc="Add 1 ""Scrap"" Tuner monster from your Deck to your hand." where id=01050684
;update texts set name="Ultimaya Tzolkin", desc="(This card''s original Level is always treated as 12.)
Cannot be Synchro Summoned. Must be Special Summoned (from your Extra Deck) by sending 2 Level 5 or higher monsters you control with the same Level to the Graveyard (1 Tuner and 1 non-Tuner), and cannot be Special Summoned by other ways. Once per turn, when a Spell/Trap Card(s) is Set on your side of the field (except during the Damage Step): You can Special Summon 1 ""Power Tool"" Synchro Monster or 1 Level 7 or 8 Dragon-Type Synchro Monster from your Extra Deck.  Cannot be targeted for attacks or by card effects, while you control another Synchro Monster." where id=01686814
;update texts set name="XX-Saber Hyunlei", desc="1 Tuner + 1 or more non-Tuner ""X-Saber"" monsters
When this card is Synchro Summoned, you can select and destroy up to 3 Spell or Trap Cards on the field." where id=02203790
;update texts set name="Road Warrior", desc="""Road Synchron"" + 2 or more non-Tuner monsters
Once per turn: You can Special Summon 1 Level 2 or lower Warrior or Machine-Type monster from your Deck." where id=02322421
;update texts set name="Power Tool Dragon", desc="1 Tuner + 1 or more non-Tuner monsters
Once per turn: You can reveal 3 Equip Spell Cards from your Deck, then your opponent randomly adds 1 of them to your hand, and you shuffle the rest back into your Deck. If this card would be destroyed while equipped with an Equip Spell Card(s), you can send 1 of those cards to the Graveyard instead." where id=02403771
;update texts set name="Crystron Phoenix", desc="1 Tuner Synchro Monster + 1 or more non-Tuner Synchro Monsters
If this card is Synchro Summoned: You can banish all Spell and Trap Cards your opponent controls and in their Graveyard. If this Synchro Summoned card is destroyed by battle or card effect: You can target 1 other monster in your Graveyard; Special Summon it." where id=02743001
;update texts set name="Wattchimera", desc="1 ""Watt"" Tuner + 1 or more non-Tuner Thunder-Type monsters
This card can attack your opponent directly. When this card inflicts Battle Damage to your opponent by a direct attack, place 1 random card from your opponent''s hand on top of their Deck." where id=02772236
;update texts set name="Naturia Barkion", desc="1 EARTH Tuner + 1 or more non-Tuner EARTH monsters 
During either player''s turn, when a Trap Card is activated: You can banish 2 cards from your Graveyard; negate the activation, and if you do, destroy it. This card must be face-up on the field to activate and to resolve this effect." where id=02956282
;update texts set name="Drill Warrior", desc="""Drill Synchron"" + 1 or more non-Tuner monsters.
Once per turn, during your Main Phase 1: You can halve this card''s ATK, and if you do, it can attack your opponent directly this turn. Once per turn: You can discard 1 card, and if you do, banish this card. During your next Standby Phase: Special Summon this card banished by this effect, then add 1 monster from your Graveyard to your hand." where id=03429238
;update texts set name="Psychic Tuning", desc="Select 1 Psychic-Type monster in your Graveyard and Special Summon it in Attack Position. It is treated as a Tuner monster. When this card is removed from the field, destroy that monster. When that monster is removed from the field, destroy this card. When this card is sent to the Graveyard, take damage equal to that monster''s Level x 400." where id=03891471
;update texts set name="Flower Cardian Boardefly", desc="1 Tuner + 2 non-Tuner monsters
If a ""Flower Cardian"" monster you control attacks a Defense Position monster, inflict piercing battle damage to your opponent. Once per turn: You can banish 1 ""Flower Cardian"" monster from your Graveyard; until the end of your opponent''s next turn, your opponent cannot activate effects of cards in the Graveyard, also they cannot Special Summon monsters from the Graveyard." where id=03966653
;update texts set name="Blackwing - Aurora the Northern Lights", desc="Cannot be Normal Summoned/Set. Must be Special Summoned (from your hand) by banishing 2 face-up monsters you control (1 ""Blackwing"" Tuner and 1 non-Tuner) and cannot be Special Summoned by other ways. Once per turn: You can banish 1 ""Blackwing"" Synchro Monster from your Extra Deck; until the End Phase, this card''s name and original ATK become that monster''s, and replace this effect with that monster''s original effects." where id=04068622
;update texts set name="Ancient Pixie Dragon", desc="1 Tuner + 1 or more non-Tuner monsters
After resolving a Field Spell Card that was activated during your turn: Draw 1 card. You can only use this effect of ""Ancient Pixie Dragon"" once per turn. Once per turn: You can target 1 face-up Attack Position monster on the field; destroy that target. There must be a face-up Field Spell Card on the field to activate and to resolve this effect." where id=04179255
;update texts set name="Splendid Rose", desc="1 Tuner + 1 or more non-Tuner monsters
Once per turn: You can banish 1 Plant-Type monster from your Graveyard, then target 1 face-up monster your opponent controls; halve that target''s ATK, until the end of this turn. During the Battle Phase, if this card attacked: You can banish 1 Plant-Type monster in your Graveyard; halve this card''s ATK until the end of this turn, and if you do, this card can make a second attack during this Battle Phase." where id=04290468
;