update texts set name="Gandora Giga Rays the Dragon of Destruction", desc="Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by sending 2 other monsters from your hand and/or field to the Graveyard. This card gains 300 ATK for each banished card. Once per turn: You can pay half your LP; apply this effect, depending on the number of ""Gandora"" monsters with different names in your Graveyard.
● 1: Destroy all other cards on the field.
● 2: Banish all other cards on the field.
● 3 or more: Banish all other cards on the field and in the Graveyards." where id=100200125
;update texts set name="Diabound Kernel", desc="When this card declares an attack: It gains&#160;?00 ATK. During either player's turn: You can target 1 face-up monster your opponent controls; it loses ATK equal to this card's ATK, then banish this card until the Standby Phase of the next turn. This ATK decrease lasts until the end of this turn. You can only use this effect of ""Diabound Kernel"" once per turn." where id=100213001
;update texts set name="Chaos Scepter Blast", desc="If you control a Level 8 or higher Spellcaster-Type monster: Banish 1 card on the field, face-down. If this card in its owner's Spell & Trap Zone is destroyed by an opponent's card effect: You can Special Summon 1 ""Magician of Black Chaos"" or ""Dark Magician of Chaos"" from your Deck, ignoring its Summoning conditions." where id=100213002
;update texts set name="Harpie's Feather Storm", desc="If you control a WIND Winged Beast-Type monster: Negate any monster effects your opponent activates this turn. If you control a ""Harpie"" monster, you can activate this card from your hand. If this card in its owner's Spell & Trap Zone is destroyed by an opponent's card effect: You can add 1 ""Harpie's Feather Duster"" from your Deck or Graveyard to your hand." where id=100213004
;update texts set name="Elemental HERO Honesty Neos", desc="During either player's turn: You can discard this card, then target 1 ""HERO"" monster you control; it gains 2500 ATK until the end of this turn. During either player’s turn: You can discard 1 ""HERO"" monster; this card gains ATK equal to the discarded monster's ATK until the end of this turn. You can only use each effect of ""Elemental HERO Honesty Neos"" once per turn." where id=100213005
;update texts set name="Skydive Scorcher", desc="Target 1 ""Elemental HERO"" Fusion Monster you control; destroy as many face-up monsters your opponent controls as possible with ATK higher than that monster's, then inflict damage to your opponent equal to the highest original ATK among those destroyed monsters in the Graveyard (your choice, if tied). If a ""Skyscraper"" Field Spell Card is in your Field Zone, the damage inflicted to your opponent instead becomes equal to the combined original ATK of those destroyed monsters in the Graveyard." where id=100213006
;update texts set name="Dark Summoning Beast", desc="You can Tribute this card; Special Summon 1 ""Uria, Lord of Searing Flames"", ""Hamon, Lord of Striking Thunder"", or ""Raviel, Lord of Phantasms"" from your hand or Deck, ignoring its Summoning conditions, also monsters you control cannot attack for the rest of this turn. You can only use this effect of ""Dark Summoning Beast"" once per turn. You can banish this card from your Graveyard; add 1 ""Uria, Lord of Searing Flames"", ""Hamon, Lord of Striking Thunder"", or “Raviel, Lord of Phantasms"" from your Deck to your hand." where id=100213007
;update texts set name="Fallen Paradise", desc="Your opponent cannot target ""Uria, Lord of Searing Flames"", ""Hamon, Lord of Striking Thunder"", ""Raviel, Lord of Phantasms"", or ""Armityle the Chaos Phantom"" in your Monster Zone with card effects, also they cannot be destroyed by your opponent's card effects. If you control ""Uria, Lord of Searing Flames"", ""Hamon, Lord of Striking Thunder"", ""Raviel, Lord of Phantasms"", or ""Armityle the Chaos Phantom"" in your Monster Zone: You can draw 2 cards. You can only use this effect of ""Fallen Paradise"" once per turn." where id=100213008
;update texts set name="Frightfur Daredevil", desc="1 ""Edge Imp"" monster + 1 ""Fluffal"" monster
When this card destroys an opponent's monster by battle: You can inflict 1000 damage to your opponent. If this card is destroyed by battle, or if this face-up card in its owner's control leaves the field because of an opponent's card effect: You can inflict 500 damage to your opponent for each ""Frightfur"" monster in your Graveyard. You can only use this effect of ""Frightfur Daredevil"" once per turn." where id=100214005
;update texts set name="Raidraptors Replica", desc="Target 1 ""Raidraptor"" monster you control; Special Summon 1 monster with the same name as that monster on the field from your Deck. While you control that face-up Special Summoned monster, monsters your opponent controls cannot target the targeted monster for attacks, also your opponent cannot target that monster with card effects." where id=100214007
;update texts set name="Brohunder", desc="When this card is Normal Summoned: You can add 1 Level 4 LIGHT Thunder-Type monster from your Deck to your hand, except ""Brohunder""." where id=100214009
;update texts set name="Celestial Double Star Shaman", desc="1 Tuner + 1 non-Tuner monster
When this card is Synchro Summoned: You can activate this effect; you cannot Special Summon monsters from the Extra Deck for the rest of this turn, except Synchro Monsters, also Special Summon up to 4 Level 2 non-Tuner monsters from your hand and/or Graveyard in Defense Position, but they have their effects negated. You can only use this effect of ""Celestial Double Star Shaman"" once per turn." where id=100214015
;update texts set name="Winged Kuriboh LV10", desc="Cannot be Normal Summoned or Set. Must be Special Summoned with ""Transcendent Wings"" and cannot be Special Summoned by other ways. During your opponent's Battle Phase: You can Tribute this face-up card; destroy all Attack Position monsters your opponent controls and inflict damage to your opponent equal to the combined original ATK of those destroyed monster(s)." where id=98585345
;update texts set name="Legacy of a HERO", desc="Return 2 Fusion Monsters that list a ""HERO"" monster as Material from your Graveyard to the Extra Deck; draw 3 cards. You can only activate 1 ""Legacy of a HERO"" per turn." where id=100214016
;update texts set name="Gozuki", desc="During your Main Phase: You can send 1 Zombie-Type monster from your Deck to the Graveyard. If this card is sent to the Graveyard: You can banish 1 Zombie-Type monster from your Graveyard, except ""Gozuki""; Special Summon 1 Zombie-Type monster from your hand. You can only use each effect of ""Gozuki"" once per turn." where id=100214017
;update texts set name="Vision HERO Vyon", desc="If this card is Normal or Special Summoned: You can send 1 ""HERO"" monster from your Deck to the Graveyard. You can only use this effect of ""Vision HERO Vyon"" once per turn. Once per turn: You can banish 1 ""HERO"" monster from your Graveyard; add 1 ""Polymerization"" from your Deck to your hand." where id=100214018
;update texts set name="Pendulumgraph of Ages", desc="Your opponent cannot target Spellcaster-Type monsters you control with Spell effects. If a face-up ""Magician"" Pendulum Monster Card(s) in your Monster Zone or Pendulum Zone leaves the field: Add 1 ""Magician"" Pendulum Monster from your Deck to your hand. You can only use this effect of ""Pendulumgraph of Ages"" once per turn." where id=100331023
;update texts set name="Startime Magician", desc="2 Level 4 ""Magician"" Pendulum Monsters
Must first be Xyz Summoned with the above Xyz Materials. Once per turn: You can detach 1 Xyz Material from this card; add to your hand, 1 face-up DARK Spellcaster-Type Pendulum Monster from your Extra Deck or 1 DARK Spellcaster-Type monster from your Deck or Graveyard. Once per turn, if a Pendulum Monster Card in your Monster Zone or Pendulum Zone would be destroyed by battle or card effect, you can send 1 Spellcaster-Type monster from your Deck to the Graveyard instead." where id=100331041
;update texts set name="Performapal Sky Magician", desc="Once per turn, if you activate a Spell Card: This card gains 300 ATK. During either player's turn: You can target 1 Continuous Spell Card you control; return it to the hand, then you can activate 1 ""Magician"" Continuous Spell Card from your hand. You can only use this effect of ""Performapal Sky Magician"" once per turn. If this face-up card leaves the field: You can target 1 card on the field; destroy it." where id=100912001
;update texts set name="Performapal Sky Pupil", desc="During either player's turn: You can return 1 Level 5 or higher ""Performapal"" monster you control to the hand; Special Summon this card from your hand. You can only use the this effect of ""Performapal Sky Pupil"" once per turn. If this card battles an opponent's monster, that monster has its effects negated until the end of the Damage Step. If this card attacks an opponent's monster, and you control another ""Performapal"" monster, before damage calculation: You can destroy that opponent's monster." where id=100912002
;update texts set name="Performapal Revue Dancer", desc="If your opponent controls a monster and you control no monsters, you can Special Summon this card (from your hand). This card can be treated as 2 Tributes for the Tribute Summon of a ""Performapal"" monster." where id=100912003
;update texts set name="Predaplant Ophrys Scorpio", desc="If this card is Normal or Special Summoned: You can send 1 monster from your hand to the Graveyard; Special Summon 1 ""Predaplant"" monster from your Deck, except ""Predaplant Ophrys Scorpio"". You can only use this effect of ""Predaplant Ophyrs Scorpio"" once per turn." where id=100912009
;update texts set name="Predaplant Darling Cobra", desc="If this card is Special Summoned by the effect of a ""Predaplant"" monster: You can add 1 ""Polymerization"" Spell Card or ""Fusion"" Spell Card from your Deck to your hand, except ""Diffusion Wave-Motion"". You can only use this effect of ""Predaplant Darling Cobra"" once per Duel." where id=100912010
;update texts set name="Predaplant Cordyceps", desc="During your Standby Phase: You can banish this card from your Graveyard, then target 2 Level 4 or lower ""Predaplant"" monsters in your Graveyard; Special Summon them, also you cannot Normal Summon/Set or Special Summon other monsters for the rest of this turn, except Fusion Monsters." where id=100912011
;update texts set name="Lyrical Luscinia - Cobalt Sparrow", desc="If this card is Special Summoned: You can add 1 Level 1 Winged Beast-Type monster from your Deck to your hand. You can only use this effect of ""Lyrical Luscinia - Cobalt Sparrow"" once per turn. A WIND Xyz Monster that was Summoned using this card on the field as Xyz Material gains this effect.
● Your opponent cannot target this card with card effects." where id=100912012
;update texts set name="Lyrical Luscinia - Sapphire Swallow", desc="If you control a Winged Beast-Type monster: You can Special Summon both this card and 1 Level 1 Winged Beast-Type monster from your hand. You can only use this effect of ""Lyrical Luscinia - Sapphire Swallow"" once per turn. A WIND Xyz Monster that was Summoned using this card on the field as Xyz Material gains this effect.
● If it is Xyz Summoned: You can target 1 ""Lyrical Luscinia"" monster in your Graveyard; attach that monster to it as Xyz Material." where id=100912013
;update texts set name="Lyrical Luscinia - Turquoise Warbler", desc="If you control no monsters, you can Special Summon this card (from your hand). If this card is Special Summoned from the hand: You can Special Summon 1 ""Lyrical Luscinia"" monster from your hand or Graveyard. You can only use this effect of ""Lyrical Luscinia - Turquoise Warbler"" once per turn." where id=100912014
;update texts set name="D/D Ghost", desc="If this card is sent to the Graveyard: You can target 1 ""Dark Contract"" card or ""D/D"" monster in your Graveyard, except ""D/D Ghost""; send 1 card with the same name as that target from your Deck to the Graveyard. If this card is banished: You can target 1 of your banished ""Dark Contract"" cards or ""D/D"" monsters, except ""D/D Ghost""; return it to the Graveyard." where id=100912015
;update texts set name="Da'at Metatron, the True Dracomechsoldier", desc="Requires 3 monster and/or Continuous Spell/Trap Card Tributes to Normal Summon/Set. Unaffected by the effects of cards with the same card type (Monster, Spell, or Trap) as the cards Tributed for the Tribute Summon of this card. If this Tribute Summoned card is destroyed by your opponent's card (by battle or card effect): You can Special Summon 1 EARTH, WATER, FIRE, or WIND Fusion, Synchro, or Xyz Monster from your Extra Deck." where id=100912025
;update texts set name="Digital Bug LED Bug", desc="Cannot be used as a Material for an Xyz Summon, except for the Xyz Summon of an Insect-Type Xyz Monster. Once per turn, when this face-up card is changed from Attack Position to Defense Position: You can add 1 Level 3 Insect-Type monster from your Deck to your hand. An Xyz Monster that was Summoned using this card on the field as Xyz Material gains this effect.
● When it destroys a monster by battle, draw 1 card." where id=100912029
;update texts set name="Performapal Gatling Ghoul", desc="1 ""Performapal"" monster + 1 Level 5 or higher DARK monster
If this card is Fusion Summoned: You can inflict 200 damage to your opponent for each card on the field, and if you do, if this card was Fusion Summoned using a Pendulum Monster as Material, destroy 1 monster your opponent controls, and if you do that, inflict damage to your opponent equal to the original ATK the destroyed monster had on the field. You can only use this effect of ""Performapal Gatling Ghoul"" once per turn." where id=100912040
;update texts set name="Lyrical Luscinia - Assembly Nightingale", desc="2 or more Level 1 monsters
This card gains 200 ATK for each Xyz Material attached to it. This card can attack your opponent directly. While this card has Xyz Material, it can attack up to that number of times during each Battle Phase. Once per turn, during either player's turn: You can detach 1 Xyz Material from this card; for the rest of this turn, ""Lyrical Luscinia"" monsters you control cannot be destroyed by battle or card effects, also you take no battle damage." where id=100912043
;update texts set name="D/D/D Boulder King Darius", desc="2 Level 3 Fiend-Type monsters
Once per turn, during either player's turn: You can detach 1 Xyz Material from this card, then target 1 ""Dark Contract"" card you control; destroy it, and if you do, draw 1 card. If this card battles an opponent's monster, during damage calculation: You can detach 1 Xyz Material from this card; this card cannot be destroyed by that battle, also destroy that opponent's monster after damage calculation, and if you do, inflict 500 damage to your opponent." where id=100912045
;update texts set name="True King V.F.D., The Beast", desc="2 or more Level 9 monsters
Once per turn, during either player's turn: You can detach 1 Xyz Material from this card, then declare 1 Attribute; for the rest of this turn, face-up monsters on the field become the declared Attribute, monsters in your opponent's possession with that Attribute cannot activate their effects, also they cannot attack. If you would destroy monsters with the effect of a ""True Draco"" or ""True King"" monster in your hand, you can also destroy monsters your opponent controls." where id=100912046
;update texts set name="Magician's Right Hand", desc="Once per turn, when a Spell Card or effect activated by your opponent resolves while you control a Spellcaster-Type monster, negate that effect, and if you do, or if it did not have an effect, destroy that card." where id=100912049
;update texts set name="Magician's Left Hand", desc="Once per turn, when a Trap Card or effect activated by your opponent resolves while you control a Spellcaster-Type monster, negate that effect, and if you do, or if it did not have an effect, destroy that card." where id=100912050
;update texts set name="Magician's Encore", desc="You can target 1 Level 3 or lower Spellcaster-Type monster in your Graveyard; Special Summon it. This effect can only be used once while this card is face-up on the field. If this card is sent to the Graveyard: You can add 1 ""Magician"" Continuous Spell Card from your Deck to your hand, except ""Magician's Encore""." where id=100912051
;update texts set name="Transcendental Polymerization", desc="Pay 2000 LP; Fusion Summon 1 Fusion Monster from your Extra Deck, using 2 monsters you control as Fusion Materials. Cards and effects cannot be activated in response to this card's activation. You can banish this card from your Graveyard, then target 1 monster Fusion Summoned by this card's effect; Special Summon all the Fusion Materials that were used for its Fusion Summon from your Graveyard, but their ATK and DEF become 0, also they have their effects negated." where id=100912052
;